from BaseClasses import Item
import typing


class ItemData(typing.NamedTuple):
    code: typing.Optional[int]
    game_id: str
    progression: bool


class DustAETItem(Item):
    game: str = "DustAET"


item_table = {
    "Victory": ItemData(None, "", True),
    "Dust Storm": ItemData(0, "~0", True),
    "Fire Projectile": ItemData(0, "~1", True),
    "Lightning Projectile": ItemData(0, "~2", True),
    "Basic Projectile": ItemData(0, "~3", True),
    "Slash": ItemData(0, "~4", True),
    "Jump": ItemData(0, "~5", True),
    "Dash": ItemData(0, "~10", True),
    "Aerial Dust Storm": ItemData(0, "~12", True),
    "Crouch Slide": ItemData(0, "~14", True),
    "Double Jump": ItemData(0, "~15", True),
    "Iron Grip": ItemData(0, "~16", True),
    "Boost Jump": ItemData(0, "~17", True),
    "FeebleFruit": ItemData(0, "0", False),
    "LoutaNut": ItemData(0, "1", False),
    "CupCake": ItemData(0, "2", False),
    "Mushroom": ItemData(0, "3", False),
    "WallChicken": ItemData(0, "4", False),
    "CinnamonBun": ItemData(0, "10", False),
    "Chaldulbagi": ItemData(0, "11", False),
    "WarmPretzel": ItemData(0, "12", False),
    "KimBap": ItemData(0, "13", False),
    "DeadlyDelight": ItemData(0, "14", False),
    "HotCocoa": ItemData(0, "15", False),
    "HotDog": ItemData(0, "16", False),
    "Doenjang": ItemData(0, "17", False),
    "Champong": ItemData(0, "18", False),
    "IceCream": ItemData(0, "19", False),
    "BirthdayCake": ItemData(0, "20", False),
    "BuffaloBurger": ItemData(0, "21", False),
    "Lasagna": ItemData(0, "22", False),
    "KingCrabLegs": ItemData(0, "23", False),
    "Galbi": ItemData(0, "24", False),
    "FilthyPendant": ItemData(0, "60", False),
    "WarpedPendant": ItemData(0, "61", False),
    "SimplePendant": ItemData(0, "62", False),
    "ChildPendant": ItemData(0, "63", False),
    "OrnamentalPendant": ItemData(0, "64", False),
    "CreaturePendant": ItemData(0, "65", False),
    "HalmeoniPendant": ItemData(0, "70", False),
    "HarabeojiPendant": ItemData(0, "71", False),
    "PoorMansPendant": ItemData(0, "72", False),
    "UglyPendant": ItemData(0, "73", False),
    "BeautyPendant": ItemData(0, "74", False),
    "SaintPendant": ItemData(0, "75", False),
    "CowardsPendant": ItemData(0, "76", False),
    "MadManPendant": ItemData(0, "77", False),
    "MarshPendant": ItemData(0, "78", False),
    "WarriorsPendant": ItemData(0, "79", False),
    "WisdomPendant": ItemData(0, "80", False),
    "BattleMastersPendant": ItemData(0, "81", False),
    "EggShellAug": ItemData(0, "120", False),
    "SandPaperAug": ItemData(0, "121", False),
    "DullWhetAug": ItemData(0, "122", False),
    "SmoothWhetAug": ItemData(0, "123", False),
    "ImpAug": ItemData(0, "124", False),
    "SpearAug": ItemData(0, "125", False),
    "GiantAug": ItemData(0, "126", False),
    "BrutalAug": ItemData(0, "127", False),
    "ScrapAug": ItemData(0, "128", False),
    "ElectricAug": ItemData(0, "129", False),
    "TeethAug": ItemData(0, "130", False),
    "TrolkFistAug": ItemData(0, "131", False),
    "FleshAug": ItemData(0, "132", False),
    "SickAug": ItemData(0, "133", False),
    "WickedAug": ItemData(0, "134", False),
    "MountaingAug": ItemData(0, "135", False),
    "FrozenAug": ItemData(0, "136", False),
    "MetalAug": ItemData(0, "137", False),
    "SoldierAug": ItemData(0, "138", False),
    "MithrarinAug": ItemData(0, "139", False),
    "LeafArmor": ItemData(0, "180", False),
    "BarkArmor": ItemData(0, "181", False),
    "CottonArmor": ItemData(0, "182", False),
    "LightChain": ItemData(0, "190", False),
    "SlimeArmor": ItemData(0, "191", False),
    "LightStoneArmor": ItemData(0, "192", False),
    "ElectricVest": ItemData(0, "193", False),
    "WetSuit": ItemData(0, "194", False),
    "MinerGear": ItemData(0, "195", False),
    "TrolkArmor": ItemData(0, "196", False),
    "DetectiveCoat": ItemData(0, "197", False),
    "WrongVest": ItemData(0, "198", False),
    "SpectralVest": ItemData(0, "199", False),
    "WarmSweater": ItemData(0, "200", False),
    "SnowSuit": ItemData(0, "201", False),
    "MountainGear": ItemData(0, "202", False),
    "LavaGear": ItemData(0, "203", False),
    "SoldierArmor": ItemData(0, "204", False),
    "MithrarinRobe": ItemData(0, "205", False),
    "DirtyRing": ItemData(0, "240", False),
    "DullRing": ItemData(0, "241", False),
    "SmoothRing": ItemData(0, "242", False),
    "LightRing": ItemData(0, "249", False),
    "ScavengerRing": ItemData(0, "250", False),
    "VigilanceRing": ItemData(0, "251", False),
    "MinerRing": ItemData(0, "252", False),
    "WealthRing": ItemData(0, "253", False),
    "ApprenticeRing": ItemData(0, "254", False),
    "ArtisanRing": ItemData(0, "255", False),
    "PatienceRing": ItemData(0, "256", False),
    "BrokenRing": ItemData(0, "257", False),
    "StudyRing": ItemData(0, "258", False),
    "FocusRing": ItemData(0, "259", False),
    "DevastationRing": ItemData(0, "260", False),
    "WeddingRing": ItemData(0, "261", False),
    "TeleportStone": ItemData(0, "300", False),
    "RevivalStone": ItemData(0, "301", False),
    "TreasureKey": ItemData(0, "305", True),
    "RedOrb": ItemData(0, "306", True),
    "FidgetDoll": ItemData(0, "307", True),
    "Cooler": ItemData(0, "308", True),
    "HaleyDevice": ItemData(0, "320", False),
    "BlueKey": ItemData(0, "321", True),
    "RedKey": ItemData(0, "322", True),
    "GreenKey": ItemData(0, "323", True),
    "YellowKey": ItemData(0, "324", True),
    "WhiteKey": ItemData(0, "325", True),
    "PurpleKey": ItemData(0, "326", True),
    "AquaKey": ItemData(0, "327", True),
    "RainbowKey": ItemData(0, "328", True),
    "CoraQuest01": ItemData(0, "330", True),
    "CoraQuest02": ItemData(0, "331", True),
    "CoraQuest03": ItemData(0, "332", True),
    "CoraQuest04": ItemData(0, "333", True),
    "BlopStick": ItemData(0, "335", False),
    "GappySheep": ItemData(0, "336", False),
    "RedMoss": ItemData(0, "337", True),
    "GianniLaundry": ItemData(0, "338", False),
    "ReedBox": ItemData(0, "339", False),
    "ReedBoxEvil": ItemData(0, "340", False),
    "GeehanWatch": ItemData(0, "341", False),
    "CoolerSnow": ItemData(0, "342", True),
    "FeebleFruit Blueprint": ItemData(0, "-0", False),
    "LoutaNut Blueprint": ItemData(0, "-1", False),
    "CupCake Blueprint": ItemData(0, "-2", False),
    "Mushroom Blueprint": ItemData(0, "-3", False),
    "WallChicken Blueprint": ItemData(0, "-4", False),
    "CinnamonBun Blueprint": ItemData(0, "-10", False),
    "Chaldulbagi Blueprint": ItemData(0, "-11", False),
    "WarmPretzel Blueprint": ItemData(0, "-12", False),
    "KimBap Blueprint": ItemData(0, "-13", False),
    "DeadlyDelight Blueprint": ItemData(0, "-14", False),
    "HotCocoa Blueprint": ItemData(0, "-15", False),
    "HotDog Blueprint": ItemData(0, "-16", False),
    "Doenjang Blueprint": ItemData(0, "-17", False),
    "Champong Blueprint": ItemData(0, "-18", False),
    "IceCream Blueprint": ItemData(0, "-19", False),
    "BirthdayCake Blueprint": ItemData(0, "-20", False),
    "BuffaloBurger Blueprint": ItemData(0, "-21", False),
    "Lasagna Blueprint": ItemData(0, "-22", False),
    "KingCrabLegs Blueprint": ItemData(0, "-23", False),
    "Galbi Blueprint": ItemData(0, "-24", False),
    "FilthyPendant Blueprint": ItemData(0, "-60", False),
    "WarpedPendant Blueprint": ItemData(0, "-61", False),
    "SimplePendant Blueprint": ItemData(0, "-62", False),
    "ChildPendant Blueprint": ItemData(0, "-63", False),
    "OrnamentalPendant Blueprint": ItemData(0, "-64", False),
    "CreaturePendant Blueprint": ItemData(0, "-65", False),
    "HalmeoniPendant Blueprint": ItemData(0, "-70", False),
    "HarabeojiPendant Blueprint": ItemData(0, "-71", False),
    "PoorMansPendant Blueprint": ItemData(0, "-72", False),
    "UglyPendant Blueprint": ItemData(0, "-73", False),
    "BeautyPendant Blueprint": ItemData(0, "-74", False),
    "SaintPendant Blueprint": ItemData(0, "-75", False),
    "CowardsPendant Blueprint": ItemData(0, "-76", False),
    "MadManPendant Blueprint": ItemData(0, "-77", False),
    "MarshPendant Blueprint": ItemData(0, "-78", False),
    "WarriorsPendant Blueprint": ItemData(0, "-79", False),
    "WisdomPendant Blueprint": ItemData(0, "-80", False),
    "BattleMastersPendant Blueprint": ItemData(0, "-81", False),
    "EggShellAug Blueprint": ItemData(0, "-120", False),
    "SandPaperAug Blueprint": ItemData(0, "-121", False),
    "DullWhetAug Blueprint": ItemData(0, "-122", False),
    "SmoothWhetAug Blueprint": ItemData(0, "-123", False),
    "ImpAug Blueprint": ItemData(0, "-124", False),
    "SpearAug Blueprint": ItemData(0, "-125", False),
    "GiantAug Blueprint": ItemData(0, "-126", False),
    "BrutalAug Blueprint": ItemData(0, "-127", False),
    "ScrapAug Blueprint": ItemData(0, "-128", False),
    "ElectricAug Blueprint": ItemData(0, "-129", False),
    "TeethAug Blueprint": ItemData(0, "-130", False),
    "TrolkFistAug Blueprint": ItemData(0, "-131", False),
    "FleshAug Blueprint": ItemData(0, "-132", False),
    "SickAug Blueprint": ItemData(0, "-133", False),
    "WickedAug Blueprint": ItemData(0, "-134", False),
    "MountaingAug Blueprint": ItemData(0, "-135", False),
    "FrozenAug Blueprint": ItemData(0, "-136", False),
    "MetalAug Blueprint": ItemData(0, "-137", False),
    "SoldierAug Blueprint": ItemData(0, "-138", False),
    "MithrarinAug Blueprint": ItemData(0, "-139", False),
    "LeafArmor Blueprint": ItemData(0, "-180", False),
    "BarkArmor Blueprint": ItemData(0, "-181", False),
    "CottonArmor Blueprint": ItemData(0, "-182", False),
    "LightChain Blueprint": ItemData(0, "-190", False),
    "SlimeArmor Blueprint": ItemData(0, "-191", False),
    "LightStoneArmor Blueprint": ItemData(0, "-192", False),
    "ElectricVest Blueprint": ItemData(0, "-193", False),
    "WetSuit Blueprint": ItemData(0, "-194", False),
    "MinerGear Blueprint": ItemData(0, "-195", False),
    "TrolkArmor Blueprint": ItemData(0, "-196", False),
    "DetectiveCoat Blueprint": ItemData(0, "-197", False),
    "WrongVest Blueprint": ItemData(0, "-198", False),
    "SpectralVest Blueprint": ItemData(0, "-199", False),
    "WarmSweater Blueprint": ItemData(0, "-200", False),
    "SnowSuit Blueprint": ItemData(0, "-201", False),
    "MountainGear Blueprint": ItemData(0, "-202", False),
    "LavaGear Blueprint": ItemData(0, "-203", False),
    "SoldierArmor Blueprint": ItemData(0, "-204", False),
    "MithrarinRobe Blueprint": ItemData(0, "-205", False),
    "DirtyRing Blueprint": ItemData(0, "-240", False),
    "DullRing Blueprint": ItemData(0, "-241", False),
    "SmoothRing Blueprint": ItemData(0, "-242", False),
    "LightRing Blueprint": ItemData(0, "-249", False),
    "ScavengerRing Blueprint": ItemData(0, "-250", False),
    "VigilanceRing Blueprint": ItemData(0, "-251", False),
    "MinerRing Blueprint": ItemData(0, "-252", False),
    "WealthRing Blueprint": ItemData(0, "-253", False),
    "ApprenticeRing Blueprint": ItemData(0, "-254", False),
    "ArtisanRing Blueprint": ItemData(0, "-255", False),
    "PatienceRing Blueprint": ItemData(0, "-256", False),
    "BrokenRing Blueprint": ItemData(0, "-257", False),
    "StudyRing Blueprint": ItemData(0, "-258", False),
    "FocusRing Blueprint": ItemData(0, "-259", False),
    "DevastationRing Blueprint": ItemData(0, "-260", False),
    "WeddingRing Blueprint": ItemData(0, "-261", False),
    "TeleportStone Blueprint": ItemData(0, "-300", False),
    "RevivalStone Blueprint": ItemData(0, "-301", False),
    "TreasureKey Blueprint": ItemData(0, "-305", True),
    "RedOrb Blueprint": ItemData(0, "-306", True),
    "FidgetDoll Blueprint": ItemData(0, "-307", True),
    "Cooler Blueprint": ItemData(0, "-308", True),
    "HaleyDevice Blueprint": ItemData(0, "-320", False),
    "BlueKey Blueprint": ItemData(0, "-321", True),
    "RedKey Blueprint": ItemData(0, "-322", True),
    "GreenKey Blueprint": ItemData(0, "-323", True),
    "YellowKey Blueprint": ItemData(0, "-324", True),
    "WhiteKey Blueprint": ItemData(0, "-325", True),
    "PurpleKey Blueprint": ItemData(0, "-326", True),
    "AquaKey Blueprint": ItemData(0, "-327", True),
    "RainbowKey Blueprint": ItemData(0, "-328", True),
    "CoraQuest01 Blueprint": ItemData(0, "-330", True),
    "CoraQuest02 Blueprint": ItemData(0, "-331", True),
    "CoraQuest03 Blueprint": ItemData(0, "-332", True),
    "CoraQuest04 Blueprint": ItemData(0, "-333", True),
    "BlopStick Blueprint": ItemData(0, "-335", False),
    "GappySheep Blueprint": ItemData(0, "-336", False),
    "RedMoss Blueprint": ItemData(0, "-337", True),
    "GianniLaundry Blueprint": ItemData(0, "-338", False),
    "ReedBox Blueprint": ItemData(0, "-339", False),
    "ReedBoxEvil Blueprint": ItemData(0, "-340", False),
    "GeehanWatch Blueprint": ItemData(0, "-341", False),
    "CoolerSnow Blueprint": ItemData(0, "-342", False),
}

i = 0
for itm in item_table:
    if item_table[itm].code == 0:
        item_table[itm] = ItemData(i+600, item_table[itm].game_id, item_table[itm].progression)
        i += 1

required_items = {
}

item_frequencies = {

}

lookup_id_to_name: typing.Dict[int, str] = {data.code: item_name for item_name, data in item_table.items() if data.code}

lookup_game_id_to_name: typing.Dict[str, str] = {data.game_id: item_name for item_name, data in item_table.items() if data.game_id}
