from BaseClasses import Location
import typing


class AdvData(typing.NamedTuple):
    id: typing.Optional[int]
    game_id: str
    vanilla_item_id: str
    region: str


class DustAETAdvancement(Location):
    game: str = "DustAET"


advancement_table = {
    "Starting Ability 1": AdvData(0, "Starting Ability 1", "~3", 'The Glade P1'),
    "Starting Ability 2": AdvData(0, "Starting Ability 2", "~4", 'The Glade P1'),
    "Starting Ability 3": AdvData(0, "Starting Ability 3", "~5", 'The Glade P1'),
    "Ability 0": AdvData(0, "Ability 0", "~0", 'The Glade P2'),
    "Ability 1": AdvData(0, "Ability 1", "~1", 'Aurora Village'),
    "Ability 2": AdvData(0, "Ability 2", "~2", 'The Sorrowing Meadow'),
    "Ability 10": AdvData(0, "Ability 10", "~10", 'The Glade P2'),
    "Ability 12": AdvData(0, "Ability 12", "~12", 'The Glade P2'),
    "Ability 14": AdvData(0, "Ability 14", "~14", 'Cirromon Caverns P1'),
    "Ability 15": AdvData(0, "Ability 15", "~15", 'Blackmoor Mountains'),
    "Ability 16": AdvData(0, "Ability 16", "~16", 'The Sorrowing Meadow'),
    "Ability 17": AdvData(0, "Ability 16", "~17", 'Blackmoor Mountains'),
    "Blue Resonance Gem": AdvData(0, "Blue Resonance Gem", "321", 'Aurora Village'),
    "Red Resonance Gem": AdvData(0, "Red Resonance Gem", "322", 'Aurora Village'),
    "Green Resonance Gem": AdvData(0, "Green Resonance Gem", "323", 'The Sorrowing Meadow'),
    "Yellow Resonance Gem": AdvData(0, "Yellow Resonance Gem", "324", 'Blackmoor Mountains'),
    "White Resonance Gem": AdvData(0, "White Resonance Gem", "325", 'Aurora Village'),
    "Rainbow Resonance Gem": AdvData(0, "Equip cave12 RainbowKey 1", "328", 'The Sorrowing Meadow'),
    "Challenge 1 Giant Augment": AdvData(0, "challenge00 0equip", "126", 'Aurora Village'),
    "Challenge 2 Key 1": AdvData(0, "challenge01 0key", "305", 'Aurora Village'),
    "Challenge 2 Wetsuit": AdvData(0, "challenge01b 0equip", "194", 'Aurora Village'),
    "Challenge 3 Spectral Vest": AdvData(0, "challenge02 0equip", "199", 'Aurora Village'),
    "Challenge 4 Warrior Pendant": AdvData(0, "challenge03 0equip", "79", 'Cirromon Caverns P2'),
    "Challenge 5 Ring": AdvData(0, "challenge04 0equip", "251", 'Cirromon Caverns P2'),
    "Challenge 6 Chest 1 Item 1": AdvData(0, "challenge05 0", "131", 'Cirromon Caverns P2'),
    "Challenge 6 Scrap Augment": AdvData(0, "challenge05 0equip", "128", 'Cirromon Caverns P2'),
    "Glade Key 1": AdvData(0, "intro01 0key", "305", 'The Glade P1'),
    "Glade Key 2": AdvData(0, "intro05 0key", "305", 'The Glade P2'),
    "Glade Key 3": AdvData(0, "intro06 0key", "305", 'The Glade P2'),
    "Glade Key 4": AdvData(0, "intro06 1key", "305", 'The Glade P2'),
    "Glade Key 5": AdvData(0, "intro07 0key", "305", 'The Glade P2'),
    "Glade Key 6": AdvData(0, "intro07b 0key", "305", 'Aurora Village'),
    "Glade Key 7": AdvData(0, "intro07b 1key", "305", 'Aurora Village'),
    "Glade Key 8": AdvData(0, "intro08c 0key", "305", 'Cirromon Caverns P1'),
    "Glade Key 9": AdvData(0, "intro08c 1key", "305", 'Cirromon Caverns P1'),
    "Glade Chest 1 Item 1": AdvData(0, "intro01b 0", "0", 'The Glade P2'),
    "Glade Chest 1 Item 2": AdvData(0, "intro01b 0", "1", 'The Glade P2'),
    "Glade Chest 1 Item 3": AdvData(0, "intro01b 0", "301", 'The Glade P2'),
    "Glade Chest 2 Item 1": AdvData(0, "intro05 0", "2", 'The Glade P2'),
    "Glade Chest 2 Item 2": AdvData(0, "intro05 0", "2", 'The Glade P2'),
    "Glade Chest 2 Item 3": AdvData(0, "intro05 0", "182", 'The Glade P2'),
    "Glade Chest 3 Item 1": AdvData(0, "intro07b 0", "0", 'The Glade P2'),
    "Glade Chest 3 Item 2": AdvData(0, "intro07b 0", "0", 'The Glade P2'),
    "Glade Chest 3 Item 3": AdvData(0, "intro07b 0", "61", 'The Glade P2'),
    "Glade Chest 4 Item 1": AdvData(0, "intro02b 0", "2", 'Cirromon Caverns P2'),
    "Glade Chest 4 Item 2": AdvData(0, "intro02b 0", "2", 'Cirromon Caverns P2'),
    "Glade Chest 4 Item 3": AdvData(0, "intro02b 0", "192", 'Cirromon Caverns P2'),
    "Glade Wall 1": AdvData(0, "intro01b 0wall", "4", 'The Glade P2'),
    "Glade Wall 2": AdvData(0, "intro01b 1wall", "4", 'The Glade P2'),
    "Glade Wall 3": AdvData(0, "intro05 0wall", "4", 'The Glade P2'),
    "Glade Wall 4": AdvData(0, "intro06 0wall", "4", 'The Glade P2'),
    "Glade Wall 5": AdvData(0, "intro06 1wall", "4", 'The Glade P2'),
    "Glade Wall 6": AdvData(0, "intro02b 0wall", "4", 'Aurora Village'),
    "Glade Wall 7": AdvData(0, "intro07b 0wall", "4", 'Aurora Village'),
    "Glade Wall 8": AdvData(0, "intro07b 1wall", "4", 'Aurora Village'),
    "Glade Wall 9": AdvData(0, "intro08 0wall", "4", 'Aurora Village'),
    "Glade Wall 10": AdvData(0, "intro08 1wall", "4", 'Aurora Village'),
    "Glade Wall 11": AdvData(0, "intro08b 0wall", "4", 'Aurora Village'),
    "Glade Wall 12": AdvData(0, "intro08b 1wall", "4", 'Aurora Village'),
    "Glade Wall 13": AdvData(0, "intro02b 1wall", "4", 'Cirromon Caverns P1'),
    "Glade Wall 14": AdvData(0, "intro08c 0wall", "4", 'Cirromon Caverns P1'),
    "Glade Wall 15": AdvData(0, "intro08c 1wall", "4", 'Cirromon Caverns P1'),
    "Glade Fidget Feeble Fruit Gift 1": AdvData(0, "Equip intro02 0 5", "0", 'The Glade P2'),
    "Glade Fidget Feeble Fruit Gift 2": AdvData(0, "Equip intro02 0 5", "0", 'The Glade P2'),
    "Glade Fidget Feeble Fruit Gift 3": AdvData(0, "Equip intro02 0 5", "0", 'The Glade P2'),
    "Glade Fidget Feeble Fruit Gift 4": AdvData(0, "Equip intro02 0 5", "0", 'The Glade P2'),
    "Glade Fidget Feeble Fruit Gift 5": AdvData(0, "Equip intro02 0 5", "0", 'The Glade P2'),
    "Glade Shopkeeper Blueprint Gift": AdvData(0, "Blueprint intro07b 190 1", "-190", 'The Glade P2'),
    "Sanctuary Standing Item": AdvData(0, "sanc02 0equip", "326", 'Aurora Village'),
    "Village Key 1": AdvData(0, "village05 0key", "305", 'Aurora Village'),
    "Village Key 2": AdvData(0, "village05 1key", "305", 'Aurora Village'),
    "Village Wall 1": AdvData(0, "village05 0wall", "4", 'Aurora Village'),
    "Village Chest 1 Item 1": AdvData(0, "village02 0", "10", 'Aurora Village'),
    "Village Chest 1 Item 2": AdvData(0, "village02 0", "10", 'Aurora Village'),
    "Village Chest 1 Item 3": AdvData(0, "village02 0", "10", 'Aurora Village'),
    "Village Chest 1 Item 4": AdvData(0, "village02 0", "3", 'Aurora Village'),
    "Village Chest 1 Item 5": AdvData(0, "village02 0", "242", 'Aurora Village'),
    "Village Chest 2 Item 1": AdvData(0, "village03 0", "10", 'Aurora Village'),
    "Village Chest 2 Item 2": AdvData(0, "village03 0", "300", 'Aurora Village'),
    "Village Chest 2 Item 3": AdvData(0, "village03 0", "62", 'Aurora Village'),
    "Village Fidget Doll 1": AdvData(0, "Equip village03 307 2", "307", 'Cirromon Caverns P1'),
    "Village Fidget Doll 2": AdvData(0, "Equip village03 307 2", "307", 'Cirromon Caverns P1'),
    "Village Hotdog 1": AdvData(0, "Equip village03 16 3", "16", 'Everdawn Basin'),
    "Village Hotdog 2": AdvData(0, "Equip village03 16 3", "16", 'Everdawn Basin'),
    "Village Hotdog 3": AdvData(0, "Equip village03 16 3", "16", 'Everdawn Basin'),
    "Village Birthday Cake 1": AdvData(0, "Equip village02alt0 BirthdayCake 2", "20", 'Cirromon Caverns P1'),
    "Village Birthday Cake 2": AdvData(0, "Equip village02alt0 BirthdayCake 2", "20", 'Cirromon Caverns P1'),
    "Village Revival Stone 1": AdvData(0, "Equip village02alt0 301 2", "301", 'Cirromon Caverns P1'),
    "Village Revival Stone 2": AdvData(0, "Equip village02alt0 301 2", "301", 'Cirromon Caverns P1'),
    "Village NPC Blueprint Gift": AdvData(0, "Blueprint village01 128 1", "-128", 'Aurora Village'),
    "Village Key Gift 1": AdvData(0, "Equip village01 TreasureKey 3", "305", 'Aurora Village'),
    "Village Key Gift 2": AdvData(0, "Equip village01 TreasureKey 3", "305", 'Aurora Village'),
    "Village Key Gift 3": AdvData(0, "Equip village01 TreasureKey 3", "305", 'Aurora Village'),
    "Ivydale Key 1": AdvData(0, "ivy01 0key", "305", 'Cirromon Caverns P2'),
    "Ivydale Key 2": AdvData(0, "ivy01 1key", "305", 'Cirromon Caverns P2'),
    "Ivydale Wall 1": AdvData(0, "ivy01 0wall", "4", 'Ivydale Glen'),
    "Ivydale Wall 2": AdvData(0, "ivy01 1wall", "4", 'Ivydale Glen'),
    "Ivydale Wall 3": AdvData(0, "ivy02 0wall", "4", 'Ivydale Glen'),
    "Ivydale Laundry": AdvData(0, "ivy02 0equip", "338", 'Ivydale Glen'),
    "Smith Chest 1 Item 1": AdvData(0, "smith03 0", "126", 'Archers\' Pass'),
    "Smith Chest 2 Item 1": AdvData(0, "smith03b 2", "301", 'Archers\' Pass'),
    "Smith Chest 3 Item 1": AdvData(0, "smith03b 0", "194", 'Archers\' Pass'),
    "Smith Chest 4 Item 1": AdvData(0, "smith03b 1", "65", 'Archers\' Pass'),
    "Smith Key 1": AdvData(0, "smith00 0key", "305", 'Archers\' Pass'),
    "Smith Key 3": AdvData(0, "smith04b 0key", "305", 'Archers\' Pass'),
    "Smith Key 4": AdvData(0, "smith04b 1key", "305", 'Archers\' Pass'),
    "Smith Key 2": AdvData(0, "smith04 0key", "305", 'Archers\' Pass'),
    "Smith Key 7": AdvData(0, "smith05 0key", "305", 'Cirromon Caverns P2'),
    "Smith Key 6": AdvData(0, "smith05 1key", "305", 'Cirromon Caverns P2'),
    "Smith Key 8": AdvData(0, "smith05 2key", "305", 'Cirromon Caverns P2'),
    "Smith Key 5": AdvData(0, "smith06 0key", "305", 'Archers\' Pass'),
    "Smith Wall 1": AdvData(0, "smith00 0wall", "4", 'Archers\' Pass'),
    "Smith Wall 2": AdvData(0, "smith04 0wall", "4", 'Archers\' Pass'),
    "Smith Wall 3": AdvData(0, "smith04 1wall", "4", 'Archers\' Pass'),
    "Smith Wall 4": AdvData(0, "smith04 2wall", "4", 'Archers\' Pass'),
    "Forest Chest 4 Item 1": AdvData(0, "forest09b 0", "16", 'Abadis Forest'),
    "Forest Chest 4 Item 2": AdvData(0, "forest09b 0", "132", 'Abadis Forest'),
    "Forest Chest 3 Item 1": AdvData(0, "forest08 0", "12", 'Abadis Forest'),
    "Forest Chest 3 Item 2": AdvData(0, "forest08 0", "12", 'Abadis Forest'),
    "Forest Chest 3 Item 3": AdvData(0, "forest08 0", "12", 'Abadis Forest'),
    "Forest Chest 3 Item 4": AdvData(0, "forest08 0", "14", 'Abadis Forest'),
    "Forest Chest 3 Item 5": AdvData(0, "forest08 0", "300", 'Abadis Forest'),
    "Forest Chest 3 Item 6": AdvData(0, "forest08 0", "305", 'Abadis Forest'),
    "Forest Chest 2 Item 1": AdvData(0, "forest04c 0", "301", 'Abadis Forest'),
    "Forest Chest 2 Item 2": AdvData(0, "forest04c 0", "200", 'Abadis Forest'),
    "Forest Chest 1 Item 1": AdvData(0, "forest02 0", "124", 'Abadis Forest'),
    "Forest Chest 1 Item 2": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 3": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 4": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 5": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 6": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 7": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 8": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 9": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 10": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Chest 1 Item 11": AdvData(0, "forest02 0", "1", 'Abadis Forest'),
    "Forest Key 1": AdvData(0, "forest03 0key", "305", 'Abadis Forest'),
    "Forest Key 2": AdvData(0, "forest07 0key", "305", 'Abadis Forest'),
    "Forest Key 3": AdvData(0, "forest08 0key", "305", 'Abadis Forest'),
    "Forest Key 4": AdvData(0, "forest08 1key", "305", 'Abadis Forest'),
    "Forest Key 5": AdvData(0, "forest09 0key", "305", 'Abadis Forest'),
    "Forest Key 6": AdvData(0, "forest11 0key", "305", 'Abadis Forest'),
    "Forest Wall 1": AdvData(0, "forest07 0wall", "4", 'Abadis Forest'),
    "Forest Wall 2": AdvData(0, "forest08c 0wall", "4", 'Abadis Forest'),
    "Forest Wall 3": AdvData(0, "forest09 0wall", "4", 'Abadis Forest'),
    "Forest Wall 4": AdvData(0, "forest09 1wall", "4", 'Abadis Forest'),
    "Forest Haley Device": AdvData(0, "forest07 0equip", "320", 'Abadis Forest'),
    "Poisioned Event Item 1": AdvData(0, "SideEvent 8 3 2", "3", 'Aurora Village'),
    "Poisioned Event Item 2": AdvData(0, "SideEvent 8 3 2", "3", 'Aurora Village'),
    "Cove Key 1": AdvData(0, "cove01b 0key", "305", 'Hidden Cove'),
    "Cove Key 2": AdvData(0, "cove01b 1key", "305", 'Hidden Cove'),
    "Cove Wall 1": AdvData(0, "cove01 0wall", "4", 'Hidden Cove'),
    "Cove Teleport Stone": AdvData(0, "cove02 0equip", "300", 'Hidden Cove'),
    "Cove Chest 1 Item 1": AdvData(0, "cove01 0", "14", 'Hidden Cove'),
    "Cove Chest 1 Item 2": AdvData(0, "cove01 0", "14", 'Hidden Cove'),
    "Cove Chest 1 Item 3": AdvData(0, "cove01 0", "14", 'Hidden Cove'),
    "Cove Chest 1 Item 4": AdvData(0, "cove01 0", "71", 'Hidden Cove'),
    "Farm Chest 1 Item 1": AdvData(0, "farm01 0", "10", 'Geehan\'s Farm'),
    "Farm Chest 1 Item 2": AdvData(0, "farm01 0", "10", 'Geehan\'s Farm'),
    "Farm Chest 1 Item 3": AdvData(0, "farm01 0", "10", 'Geehan\'s Farm'),
    "Farm Chest 1 Item 4": AdvData(0, "farm01 0", "191", 'Geehan\'s Farm'),
    "Farm Wall 1": AdvData(0, "farm01 0wall", "4", 'Geehan\'s Farm'),
    "Farm Wall 2": AdvData(0, "farm01 1wall", "4", 'Geehan\'s Farm'),
    "Farm Wall 3": AdvData(0, "farm01 2wall", "4", 'Geehan\'s Farm'),
    "Farm Wall 4": AdvData(0, "farm01 3wall", "4", 'Geehan\'s Farm'),
    "Farm Wall 5": AdvData(0, "farm01 4wall", "4", 'Geehan\'s Farm'),
    "Farm Wall 6": AdvData(0, "farm02 0wall", "4", 'Geehan\'s Farm'),
    "Farm Watch": AdvData(0, "farm02 0equip", "341", 'Geehan\'s Farm'),
    "Cave Wall 1": AdvData(0, "cave02b 0wall", "4", 'Cirromon Caverns P1'),
    "Cave Wall 2": AdvData(0, "cave02b 1wall", "4", 'Cirromon Caverns P2'),
    "Cave Key 1": AdvData(0, "cave02 0key", "305", 'Cirromon Caverns P1'),
    "Cave Key 2": AdvData(0, "cave02b 0key", "305", 'Cirromon Caverns P2'),
    "Cave Key 3": AdvData(0, "cave02b 1key", "305", 'Cirromon Caverns P2'),
    "Cave Key 4": AdvData(0, "cave02b 2key", "305", 'Cirromon Caverns P2'),
    "Cave Key 5": AdvData(0, "cave05b 0key", "305", 'Cirromon Caverns P1'),
    "Cave Key 6": AdvData(0, "cave05b 1key", "305", 'Cirromon Caverns P1'),
    "Cave Key 7": AdvData(0, "cave05b 2key", "305", 'Cirromon Caverns P1'),
    "Cave Key 8": AdvData(0, "cave08 0key", "305", 'Cirromon Caverns P1'),
    "Cave Key 9": AdvData(0, "cave12 0key", "305", 'Cirromon Caverns P1'),
    "Cave Key 10": AdvData(0, "cave12b 0key", "305", 'The Sorrowing Meadow'),
    "Cave Key 11": AdvData(0, "cave12b 1key", "305", 'Cirromon Caverns P1'),
    "Cave Key 12": AdvData(0, "cave12b 2key", "305", 'Cirromon Caverns P1'),
    "Cave Key 13": AdvData(0, "cave13 0key", "305", 'Cirromon Caverns P1'),
    "Cave Key 14": AdvData(0, "cave19 0key", "305", 'Cirromon Caverns P2'),
    "Cave Key 15": AdvData(0, "cave21 0key", "305", 'Cirromon Caverns P2'),
    "Cave Key 16": AdvData(0, "cave21 1key", "305", 'Cirromon Caverns P2'),
    "Cave Key 17": AdvData(0, "cave23 0key", "305", 'The Sorrowing Meadow'),
    "Cave Key 18": AdvData(0, "cave27 0key", "305", 'Cirromon Caverns P2'),
    "Cave Wall 4": AdvData(0, "cave12 0wall", "4", 'Cirromon Caverns P1'),
    "Cave Wall 5": AdvData(0, "cave12 1wall", "4", 'Cirromon Caverns P2'),
    "Cave Wall 6": AdvData(0, "cave13 0wall", "4", 'The Sorrowing Meadow'),
    "Cave Wall 7": AdvData(0, "cave15 0wall", "4", 'Cirromon Caverns P1'),
    "Cave Wall 9": AdvData(0, "cave27 0wall", "4", 'Cirromon Caverns P1'),
    "Cave Wall 8": AdvData(0, "cave19 0wall", "4", 'The Sorrowing Meadow'),
    "Cave Chest 2 Item 1": AdvData(0, "cave04 0", "-252", 'Cirromon Caverns P1'),
    "Cave Chest 9 Item 1": AdvData(0, "cave27 0", "-254", 'The Sorrowing Meadow'),
    "Cave Chest 8 Item 1": AdvData(0, "cave24 0", "13", 'The Sorrowing Meadow'),
    "Cave Chest 8 Item 2": AdvData(0, "cave24 0", "13", 'The Sorrowing Meadow'),
    "Cave Chest 8 Item 3": AdvData(0, "cave24 0", "13", 'The Sorrowing Meadow'),
    "Cave Chest 8 Item 4": AdvData(0, "cave24 0", "13", 'The Sorrowing Meadow'),
    "Cave Chest 8 Item 5": AdvData(0, "cave24 0", "13", 'The Sorrowing Meadow'),
    "Cave Chest 8 Item 6": AdvData(0, "cave24 0", "249", 'The Sorrowing Meadow'),
    "Cave Chest 7 Item 1": AdvData(0, "cave22 0", "-195", 'The Sorrowing Meadow'),
    "Cave Chest 6 Item 1": AdvData(0, "cave19b 0", "-139", 'Cirromon Caverns P2'),
    "Cave Chest 5 Item 1": AdvData(0, "cave17 0", "15", 'The Sorrowing Meadow'),
    "Cave Chest 5 Item 2": AdvData(0, "cave17 0", "12", 'The Sorrowing Meadow'),
    "Cave Chest 5 Item 3": AdvData(0, "cave17 0", "12", 'The Sorrowing Meadow'),
    "Cave Chest 5 Item 4": AdvData(0, "cave17 0", "12", 'The Sorrowing Meadow'),
    "Cave Chest 5 Item 5": AdvData(0, "cave17 0", "12", 'The Sorrowing Meadow'),
    "Cave Chest 5 Item 6": AdvData(0, "cave17 0", "12", 'The Sorrowing Meadow'),
    "Cave Chest 5 Item 7": AdvData(0, "cave17 0", "73", 'The Sorrowing Meadow'),
    "Cave Chest 4 Item 1": AdvData(0, "cave05b 0", "15", 'Cirromon Caverns P1'),
    "Cave Chest 4 Item 2": AdvData(0, "cave05b 0", "13", 'Cirromon Caverns P1'),
    "Cave Chest 4 Item 3": AdvData(0, "cave05b 0", "250", 'Cirromon Caverns P1'),
    "Cave Chest 3 Item 1": AdvData(0, "cave04 1", "10", 'Cirromon Caverns P1'),
    "Cave Chest 3 Item 2": AdvData(0, "cave04 1", "10", 'Cirromon Caverns P1'),
    "Cave Chest 3 Item 3": AdvData(0, "cave04 1", "10", 'Cirromon Caverns P1'),
    "Cave Chest 3 Item 4": AdvData(0, "cave04 1", "-70", 'Cirromon Caverns P1'),
    "Cave Chest 1 Item 1": AdvData(0, "cave02 0", "127", 'Cirromon Caverns P1'),
    "Cave Chest 1 Item 2": AdvData(0, "cave02 0", "12", 'Cirromon Caverns P1'),
    "Cave Chest 1 Item 3": AdvData(0, "cave02 0", "12", 'Cirromon Caverns P1'),
    "Cave Chest 1 Item 4": AdvData(0, "cave02 0", "12", 'Cirromon Caverns P1'),
    "Cave Wall 3": AdvData(0, "cave05b 0wall", "4", 'Cirromon Caverns P1'),
    "Cave Light Ring": AdvData(0, "Equip cave12 249 1", "249", 'Cirromon Caverns P2'),
    "Cave Doenjang 1": AdvData(0, "Equip cave12 Doenjang 3", "17", 'Cirromon Caverns P1'),
    "Cave Doenjang 2": AdvData(0, "Equip cave12 Doenjang 3", "17", 'Cirromon Caverns P1'),
    "Cave Doenjang 3": AdvData(0, "Equip cave12 Doenjang 3", "17", 'Cirromon Caverns P1'),
    "Cave Reed's Box": AdvData(0, "Equip cave12 ReedBox 1", "339", 'Cirromon Caverns P1'),
    "Cave Sheep 1": AdvData(0, "Equip cave08 0 GappySheep 1", "336", 'Cirromon Caverns P2'),
    "Cave Sheep 2": AdvData(0, "Equip cave12 0 GappySheep 1", "336", 'Cirromon Caverns P2'),
    "Cave Sheep 3": AdvData(0, "Equip cave12 1 GappySheep 1", "336", 'The Sorrowing Meadow'),
    "Cave Sheep 4": AdvData(0, "Equip cave13 0 GappySheep 1", "336", 'Cirromon Caverns P1'),
    "Cave Sheep 5": AdvData(0, "Equip cave15 0 GappySheep 1", "336", 'Cirromon Caverns P1'),
    "Cave Sheep 6": AdvData(0, "Equip cave21 0 GappySheep 1", "336", 'The Sorrowing Meadow'),
    "Cave Red Moss 1": AdvData(0, "cave24 0equip", "337", 'The Sorrowing Meadow'),
    "Cave Red Moss 2": AdvData(0, "cave24 1equip", "337", 'The Sorrowing Meadow'),
    "Cave Red Moss 3": AdvData(0, "cave24 2equip", "337", 'The Sorrowing Meadow'),
    "Cave Stick": AdvData(0, "cave14 0equip", "335", 'The Sorrowing Meadow'),
    "Cave Red Orb": AdvData(0, "cave15 1equip", "306", 'Cirromon Caverns P1'),
    "Meadow Key 1": AdvData(0, "grave03 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 2": AdvData(0, "grave04 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 3": AdvData(0, "grave04 1key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 4": AdvData(0, "grave04 2key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 5": AdvData(0, "grave07 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 6": AdvData(0, "grave07 1key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 7": AdvData(0, "grave11 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 8": AdvData(0, "grave20 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 9": AdvData(0, "grave21 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 10": AdvData(0, "grave21 1key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 11": AdvData(0, "grave21 2key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 12": AdvData(0, "grave23 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 13": AdvData(0, "grave24 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 14": AdvData(0, "grave24 1key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 15": AdvData(0, "grave13 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 16": AdvData(0, "grave13b 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 17": AdvData(0, "grave13b 1key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 18": AdvData(0, "grave13b 2key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 19": AdvData(0, "grave22 0key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 20": AdvData(0, "grave22 1key", "305", 'The Sorrowing Meadow'),
    "Meadow Key 21": AdvData(0, "grave22 2key", "305", 'The Sorrowing Meadow'),
    "Meadow Chest 11 Item 1": AdvData(0, "grave24 0", "16", 'The Sorrowing Meadow'),
    "Meadow Chest 11 Item 2": AdvData(0, "grave24 0", "16", 'The Sorrowing Meadow'),
    "Meadow Chest 11 Item 3": AdvData(0, "grave24 0", "16", 'The Sorrowing Meadow'),
    "Meadow Chest 11 Item 4": AdvData(0, "grave24 0", "16", 'The Sorrowing Meadow'),
    "Meadow Chest 11 Item 5": AdvData(0, "grave24 0", "15", 'The Sorrowing Meadow'),
    "Meadow Chest 11 Item 6": AdvData(0, "grave24 0", "15", 'The Sorrowing Meadow'),
    "Meadow Chest 10 Item 1": AdvData(0, "grave22 0", "253", 'The Sorrowing Meadow'),
    "Meadow Chest 10 Item 2": AdvData(0, "grave22 0", "11", 'The Sorrowing Meadow'),
    "Meadow Chest 10 Item 3": AdvData(0, "grave22 0", "11", 'The Sorrowing Meadow'),
    "Meadow Chest 10 Item 4": AdvData(0, "grave22 0", "11", 'The Sorrowing Meadow'),
    "Meadow Chest 10 Item 5": AdvData(0, "grave22 0", "11", 'The Sorrowing Meadow'),
    "Meadow Chest 10 Item 6": AdvData(0, "grave22 0", "11", 'The Sorrowing Meadow'),
    "Meadow Chest 9 Item 1": AdvData(0, "grave14 0", "18", 'The Sorrowing Meadow'),
    "Meadow Chest 9 Item 2": AdvData(0, "grave14 0", "-134", 'The Sorrowing Meadow'),
    "Meadow Chest 8 Item 1": AdvData(0, "grave13 0", "16", 'The Sorrowing Meadow'),
    "Meadow Chest 8 Item 2": AdvData(0, "grave13 0", "16", 'The Sorrowing Meadow'),
    "Meadow Chest 8 Item 3": AdvData(0, "grave13 0", "16", 'The Sorrowing Meadow'),
    "Meadow Chest 8 Item 4": AdvData(0, "grave13 0", "-198", 'The Sorrowing Meadow'),
    "Meadow Chest 7 Item 1": AdvData(0, "grave07 0", "76", 'The Sorrowing Meadow'),
    "Meadow Wall 4": AdvData(0, "grave07 0wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 5": AdvData(0, "grave07 1wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 6": AdvData(0, "grave07 2wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 7": AdvData(0, "grave09 0wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 8": AdvData(0, "grave09 1wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 9": AdvData(0, "grave09 2wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 10": AdvData(0, "grave11 0wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 11": AdvData(0, "grave11 1wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 12": AdvData(0, "grave15 0wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 13": AdvData(0, "grave15 1wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 14": AdvData(0, "grave15 2wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 15": AdvData(0, "grave15 3wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 16": AdvData(0, "grave15 4wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 17": AdvData(0, "grave20 0wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 18": AdvData(0, "grave20 1wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 19": AdvData(0, "grave20 2wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 20": AdvData(0, "grave20 3wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 21": AdvData(0, "grave20 4wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 22": AdvData(0, "grave20 5wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 23": AdvData(0, "grave24 0wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 24": AdvData(0, "grave24 1wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 25": AdvData(0, "grave24 2wall", "4", 'The Sorrowing Meadow'),
    "Meadow Wall 26": AdvData(0, "grave24 3wall", "4", 'The Sorrowing Meadow'),
    "Meadow Chest 6 Item 1": AdvData(0, "grave05 0", "-132", 'The Sorrowing Meadow'),
    "Meadow Chest 5 Item 1": AdvData(0, "grave09 0", "197", 'The Sorrowing Meadow'),
    "Meadow Chest 4 Item 1": AdvData(0, "grave08 0", "-256", 'Cirromon Caverns P1'),
    "Meadow Chest 3 Item 1": AdvData(0, "grave04 0", "305", 'The Sorrowing Meadow'),
    "Meadow Wall 3": AdvData(0, "grave04 0wall", "4", 'The Sorrowing Meadow'),
    "Meadow Chest 2 Item 1": AdvData(0, "grave03 0", "74", 'The Sorrowing Meadow'),
    "Meadow Chest 2 Item 2": AdvData(0, "grave03 0", "14", 'The Sorrowing Meadow'),
    "Meadow Chest 2 Item 3": AdvData(0, "grave03 0", "14", 'The Sorrowing Meadow'),
    "Meadow Chest 2 Item 4": AdvData(0, "grave03 0", "14", 'The Sorrowing Meadow'),
    "Meadow Chest 1 Item 1": AdvData(0, "grave01b 0", "17", 'Blackmoor Mountains'),
    "Meadow Chest 1 Item 2": AdvData(0, "grave01b 0", "17", 'Blackmoor Mountains'),
    "Meadow Chest 1 Item 3": AdvData(0, "grave01b 0", "17", 'Blackmoor Mountains'),
    "Meadow Wall 1": AdvData(0, "grave01b 0wall", "4", 'Blackmoor Mountains'),
    "Meadow Wall 2": AdvData(0, "grave03 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion A Item": AdvData(0, "mansiona02 0equip", "330", 'The Sorrowing Meadow'),
    "Mansion A Key 1": AdvData(0, "mansiona01 0key", "305", 'The Sorrowing Meadow'),
    "Mansion A Wall 1": AdvData(0, "mansiona01 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion A Wall 2": AdvData(0, "mansiona01 1wall", "4", 'The Sorrowing Meadow'),
    "Mansion A Wall 3": AdvData(0, "mansiona01 2wall", "4", 'The Sorrowing Meadow'),
    "Mansion A Wall 4": AdvData(0, "mansiona01 3wall", "4", 'The Sorrowing Meadow'),
    "Mansion A Wall 5": AdvData(0, "mansiona01 4wall", "4", 'The Sorrowing Meadow'),
    "Mansion A Wall 6": AdvData(0, "mansiona01 5wall", "4", 'The Sorrowing Meadow'),
    "Mansion A Wall 7": AdvData(0, "mansiona01 6wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Chest 1 Item 1": AdvData(0, "mansionb01 0", "-75", 'The Sorrowing Meadow'),
    "Mansion B Key 1": AdvData(0, "mansionb01 0key", "305", 'The Sorrowing Meadow'),
    "Mansion B Wall 1": AdvData(0, "mansionb01 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Wall 2": AdvData(0, "mansionb01 1wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Wall 3": AdvData(0, "mansionb01 2wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Wall 4": AdvData(0, "mansionb01 3wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Wall 5": AdvData(0, "mansionb01 4wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Wall 6": AdvData(0, "mansionb01 5wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Wall 7": AdvData(0, "mansionb02 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Wall 8": AdvData(0, "mansionb02 1wall", "4", 'The Sorrowing Meadow'),
    "Mansion B Key 2": AdvData(0, "mansionb03 0key", "305", 'The Sorrowing Meadow'),
    "Mansion B Item": AdvData(0, "mansionb03 0equip", "331", 'The Sorrowing Meadow'),
    "Mansion C Key 1": AdvData(0, "mansionc01 0key", "305", 'The Sorrowing Meadow'),
    "Mansion C Key 2": AdvData(0, "mansionc01 1key", "305", 'The Sorrowing Meadow'),
    "Mansion C Key 3": AdvData(0, "mansionc01 2key", "305", 'The Sorrowing Meadow'),
    "Mansion C Key 4": AdvData(0, "mansionc03 0key", "305", 'The Sorrowing Meadow'),
    "Mansion C Wall 1": AdvData(0, "mansionc01 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 2": AdvData(0, "mansionc01 1wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 3": AdvData(0, "mansionc01 2wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 4": AdvData(0, "mansionc01 3wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 5": AdvData(0, "mansionc01 4wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 6": AdvData(0, "mansionc02 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 7": AdvData(0, "mansionc02 1wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 8": AdvData(0, "mansionc02 2wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Wall 9": AdvData(0, "mansionc02 3wall", "4", 'The Sorrowing Meadow'),
    "Mansion C Chest 1 Item 1": AdvData(0, "mansionc02 0", "-199", 'The Sorrowing Meadow'),
    "Mansion C Item": AdvData(0, "mansionc04 0equip", "332", 'The Sorrowing Meadow'),
    "Mansion D Key 1": AdvData(0, "mansiond01 0key", "305", 'The Sorrowing Meadow'),
    "Mansion D Chest 1 Item 1": AdvData(0, "mansiond02 0", "-133", 'The Sorrowing Meadow'),
    "Mansion D Chest 2 Item 1": AdvData(0, "mansiond02 1", "-255", 'The Sorrowing Meadow'),
    "Mansion D Wall 1": AdvData(0, "mansiond01 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 2": AdvData(0, "mansiond01 1wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 3": AdvData(0, "mansiond02 0wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 4": AdvData(0, "mansiond02 1wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 5": AdvData(0, "mansiond02 2wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 6": AdvData(0, "mansiond02 3wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 7": AdvData(0, "mansiond02 4wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 8": AdvData(0, "mansiond02 5wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Wall 9": AdvData(0, "mansiond02 6wall", "4", 'The Sorrowing Meadow'),
    "Mansion D Item": AdvData(0, "mansiond02 0equip", "333", 'The Sorrowing Meadow'),
    "Mountain Cooler": AdvData(0, "snow10 0equip", "308", 'Blackmoor Mountains'),
    "Mountain Key 1": AdvData(0, "snow03 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 2": AdvData(0, "snow03 1key", "305", 'Blackmoor Mountains'),
    "Mountain Key 3": AdvData(0, "snow05 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 4": AdvData(0, "snow06 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 5": AdvData(0, "snow06 1key", "305", 'Blackmoor Mountains'),
    "Mountain Key 6": AdvData(0, "snow07 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 7": AdvData(0, "snow07 1key", "305", 'Blackmoor Mountains'),
    "Mountain Key 8": AdvData(0, "snow11 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 9": AdvData(0, "snow12 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 10": AdvData(0, "snow14 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 11": AdvData(0, "snow15 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 12": AdvData(0, "snow17 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 13": AdvData(0, "snow18 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 14": AdvData(0, "snow21 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 15": AdvData(0, "snow22 0key", "305", 'Blackmoor Mountains'),
    "Mountain Key 16": AdvData(0, "snow22 1key", "305", 'Blackmoor Mountains'),
    "Mountain Wall 1": AdvData(0, "snow08 0wall", "4", 'Blackmoor Mountains'),
    "Mountain Wall 2": AdvData(0, "snow11 0wall", "4", 'Blackmoor Mountains'),
    "Mountain Wall 3": AdvData(0, "snow13 0wall", "4", 'Blackmoor Mountains'),
    "Mountain Wall 4": AdvData(0, "snow14 0wall", "4", 'Blackmoor Mountains'),
    "Mountain Wall 5": AdvData(0, "snow23 0wall", "4", 'Blackmoor Mountains'),
    "Mountain Wall 6": AdvData(0, "snow23 1wall", "4", 'Blackmoor Mountains'),
    "Mountain Chest 1 Item 1": AdvData(0, "snow02 0", "19", 'Blackmoor Mountains'),
    "Mountain Chest 1 Item 2": AdvData(0, "snow02 0", "19", 'Blackmoor Mountains'),
    "Mountain Chest 1 Item 3": AdvData(0, "snow02 0", "19", 'Blackmoor Mountains'),
    "Mountain Chest 1 Item 4": AdvData(0, "snow02 0", "-77", 'Blackmoor Mountains'),
    "Mountain Chest 2 Item 1": AdvData(0, "snow04 1", "-257", 'Blackmoor Mountains'),
    "Mountain Chest 3 Item 1": AdvData(0, "snow05 0", "-201", 'Blackmoor Mountains'),
    "Mountain Chest 4 Item 1": AdvData(0, "snow07 0", "258", 'Blackmoor Mountains'),
    "Mountain Chest 5 Item 1": AdvData(0, "snow11 0", "21", 'Blackmoor Mountains'),
    "Mountain Chest 5 Item 2": AdvData(0, "snow11 0", "21", 'Blackmoor Mountains'),
    "Mountain Chest 5 Item 3": AdvData(0, "snow11 0", "-78", 'Blackmoor Mountains'),
    "Mountain Chest 6 Item 1": AdvData(0, "snow14 0", "200", 'Blackmoor Mountains'),
    "Mountain Chest 7 Item 1": AdvData(0, "snow20 0", "19", 'Blackmoor Mountains'),
    "Mountain Chest 7 Item 2": AdvData(0, "snow20 0", "-78", 'Blackmoor Mountains'),
    "Mountain Chest 8 Item 1": AdvData(0, "snow21 0", "300", 'Blackmoor Mountains'),
    "Mountain Chest 8 Item 2": AdvData(0, "snow21 0", "-136", 'Blackmoor Mountains'),
    "Mountain Chest 9 Item 1": AdvData(0, "snow22 0", "-79", 'Blackmoor Mountains'),
    "Mountain Chest 10 Item 1": AdvData(0, "snow23 0", "20", 'Blackmoor Mountains'),
    "Mountain Chest 10 Item 2": AdvData(0, "snow23 0", "20", 'Blackmoor Mountains'),
    "Mountain Chest 10 Item 3": AdvData(0, "snow23 0", "20", 'Blackmoor Mountains'),
    "Mountain Chest 10 Item 4": AdvData(0, "snow23 0", "20", 'Blackmoor Mountains'),
    "Mountain Chest 11 Item 1": AdvData(0, "snow23 1", "259", 'Blackmoor Mountains'),
    "Mountain Chest 12 Item 1": AdvData(0, "snow25 0", "-202", 'Blackmoor Mountains'),
    "Snow-filled Cooler": AdvData(0, "Equip lava08 342 1", "342", 'Blackmoor Mountains'),
    "Lava Chest 1 Item 1": AdvData(0, "lava02 0", "258", 'Everdawn Basin'),
    "Lava Chest 2 Item 1": AdvData(0, "lava07 0", "23", 'Everdawn Basin'),
    "Lava Chest 2 Item 2": AdvData(0, "lava07 0", "23", 'Everdawn Basin'),
    "Lava Chest 2 Item 3": AdvData(0, "lava07 0", "-203", 'Everdawn Basin'),
    "Lava Chest 3 Item 1": AdvData(0, "lava08b 0", "-80", 'Everdawn Basin'),
    "Lava Chest 4 Item 1": AdvData(0, "lava08b 1", "253", 'Everdawn Basin'),
    "Lava Chest 4 Item 2": AdvData(0, "lava08b 1", "24", 'Everdawn Basin'),
    "Lava Chest 5 Item 1": AdvData(0, "lava09 0", "16", 'Everdawn Basin'),
    "Lava Chest 5 Item 2": AdvData(0, "lava09 0", "16", 'Everdawn Basin'),
    "Lava Chest 5 Item 3": AdvData(0, "lava09 0", "16", 'Everdawn Basin'),
    "Lava Chest 5 Item 4": AdvData(0, "lava09 0", "16", 'Everdawn Basin'),
    "Lava Chest 5 Item 5": AdvData(0, "lava09 0", "12", 'Everdawn Basin'),
    "Lava Chest 5 Item 6": AdvData(0, "lava09 0", "12", 'Everdawn Basin'),
    "Lava Chest 5 Item 7": AdvData(0, "lava09 0", "12", 'Everdawn Basin'),
    "Lava Chest 5 Item 8": AdvData(0, "lava09 0", "12", 'Everdawn Basin'),
    "Lava Chest 5 Item 9": AdvData(0, "lava09 0", "15", 'Everdawn Basin'),
    "Lava Chest 5 Item 10": AdvData(0, "lava09 0", "15", 'Everdawn Basin'),
    "Lava Chest 5 Item 11": AdvData(0, "lava09 0", "15", 'Everdawn Basin'),
    "Lava Chest 5 Item 12": AdvData(0, "lava09 0", "15", 'Everdawn Basin'),
    "Lava Chest 6 Item 1": AdvData(0, "lava09 1", "305", 'Everdawn Basin'),
    "Lava Chest 7 Item 1": AdvData(0, "lava11b 0", "-204", 'Everdawn Basin'),
    "Lava Chest 8 Item 1": AdvData(0, "lava12 0", "-260", 'Everdawn Basin'),
    "Lava Chest 9 Item 1": AdvData(0, "lava13 0", "22", 'Everdawn Basin'),
    "Lava Chest 9 Item 2": AdvData(0, "lava13 0", "22", 'Everdawn Basin'),
    "Lava Chest 9 Item 3": AdvData(0, "lava13 0", "22", 'Everdawn Basin'),
    "Lava Chest 9 Item 4": AdvData(0, "lava13 0", "22", 'Everdawn Basin'),
    "Lava Chest 10 Item 1": AdvData(0, "lava15 0", "21", 'Everdawn Basin'),
    "Lava Chest 10 Item 2": AdvData(0, "lava15 0", "21", 'Everdawn Basin'),
    "Lava Chest 11 Item 1": AdvData(0, "lava16 0", "-138", 'Everdawn Basin'),
    "Lava Chest 12 Item 1": AdvData(0, "lava18b 0", "261", 'Everdawn Basin'),
    "Lava Key 1": AdvData(0, "lava03 0key", "305", 'Everdawn Basin'),
    "Lava Key 2": AdvData(0, "lava03 1key", "305", 'Everdawn Basin'),
    "Lava Key 3": AdvData(0, "lava09 0key", "305", 'Everdawn Basin'),
    "Lava Key 4": AdvData(0, "lava09 1key", "305", 'Everdawn Basin'),
    "Lava Key 5": AdvData(0, "lava09b 0key", "305", 'Everdawn Basin'),
    "Lava Key 6": AdvData(0, "lava09b 1key", "305", 'Everdawn Basin'),
    "Lava Key 7": AdvData(0, "lava09b 1key", "305", 'Everdawn Basin'),
    "Lava Key 8": AdvData(0, "lava09b 2key", "305", 'Everdawn Basin'),
    "Lava Key 9": AdvData(0, "lava09b 3key", "305", 'Everdawn Basin'),
    "Lava Key 10": AdvData(0, "lava13 0key", "305", 'Everdawn Basin'),
    "Lava Key 11": AdvData(0, "lava15 0key", "305", 'Everdawn Basin'),
    "Lava Key 12": AdvData(0, "lava15 1key", "305", 'Everdawn Basin'),
    "Lava Key 13": AdvData(0, "lava15 2key", "305", 'Everdawn Basin'),
    "Lava Key 14": AdvData(0, "lava17 0key", "305", 'Everdawn Basin'),
    "Lava Key 15": AdvData(0, "lava17 1key", "305", 'Everdawn Basin'),
    "Lava Key 16": AdvData(0, "lava18 0key", "305", 'Everdawn Basin'),
    "Lava Wall 1": AdvData(0, "lava08 0wall", "4", 'Everdawn Basin'),
    "Lava Wall 2": AdvData(0, "lava12 0wall", "4", 'Everdawn Basin'),
    "Lava Wall 3": AdvData(0, "lava15 0wall", "4", 'Everdawn Basin'),
    "Lava Wall 4": AdvData(0, "lava15 1wall", "4", 'Everdawn Basin'),
    "Lava Wall 5": AdvData(0, "lava16 0wall", "4", 'Everdawn Basin'),
    "Lava Wall 6": AdvData(0, "lava17 0wall", "4", 'Everdawn Basin'),
    "Lava Wall 7": AdvData(0, "lava17 1wall", "4", 'Everdawn Basin'),
    "General Gaius": AdvData(None, "", "", 'Everdawn Basin'),
}

i = 0
for adv in advancement_table:
    if advancement_table[adv].id is not None:
        advancement_table[adv] = AdvData(i+9683000, advancement_table[adv].game_id, advancement_table[adv].vanilla_item_id, advancement_table[adv].region)
        i += 1
    else:
        advancement_table[adv] = AdvData(None, advancement_table[adv].game_id, advancement_table[adv].vanilla_item_id, advancement_table[adv].region)

exclusion_table = {
}

events_table = {
}

lookup_id_to_name: typing.Dict[int, str] = {data.id: item_name for item_name, data in advancement_table.items() if data.id}