from BaseClasses import Item, ItemClassification
import typing


class ItemData(typing.NamedTuple):
    code: typing.Optional[int]
    classification: any
    setId: str


class ShopData(typing.NamedTuple):
    setId: str
    atmosphere: int = 0
    health: int = 0
    entertainment: int = 0
    liability: int = 0
    revenue: int = 0


class FFPSItem(Item):
    game: str = "FFPS"


shop_table = [
    ShopData("101", entertainment=1, revenue=1),
    ShopData("102", entertainment=3, liability=1),
    ShopData("103", health=1),
    ShopData("104", atmosphere=1, health=1),
    ShopData("105"),
    ShopData("106"),
    ShopData("107", health=3),
    ShopData("108", atmosphere=1, health=2),
    ShopData("109", entertainment=2, revenue=1),
    ShopData("110", entertainment=1),
    ShopData("111", entertainment=1),
    ShopData("112", entertainment=3, liability=1),
    ShopData("113", entertainment=1),
    ShopData("114", entertainment=1),
    ShopData("115", atmosphere=1),
    ShopData("201", atmosphere=3, health=2),
    ShopData("202", atmosphere=3),
    ShopData("203", atmosphere=8),
    ShopData("204", entertainment=3, revenue=1),
    ShopData("205", entertainment=4, revenue=1),
    ShopData("206", entertainment=1, revenue=3),
    ShopData("207", entertainment=2, atmosphere=2),
    ShopData("208"),
    ShopData("209"),
    ShopData("210", atmosphere=5),
    ShopData("211", entertainment=4),
    ShopData("212", entertainment=4),
    ShopData("213", entertainment=5, liability=1),
    ShopData("214", entertainment=4),
    ShopData("215", entertainment=3, revenue=3),
    ShopData("301"),
    ShopData("302"),
    ShopData("303", entertainment=6, liability=3),
    ShopData("304", entertainment=7, liability=4),
    ShopData("305", entertainment=5, revenue=4),
    ShopData("306", entertainment=4, liability=1, revenue=5),
    ShopData("307", atmosphere=3, entertainment=1, revenue=1),
    ShopData("308", atmosphere=3, entertainment=2, revenue=1),
    ShopData("309", entertainment=5, revenue=5),
    ShopData("310", health=5),
    ShopData("311", health=7),
    ShopData("312", entertainment=7, liability=1),
    ShopData("313", entertainment=7, liability=1),
    ShopData("314", entertainment=7, liability=1),
    ShopData("315", entertainment=8, liability=1),
    ShopData("401", entertainment=6, revenue=4),
    ShopData("402", atmosphere=9, entertainment=2, health=2),
    ShopData("403", entertainment=8, liability=4),
    ShopData("404", atmosphere=4, entertainment=4),
    ShopData("405", atmosphere=5, entertainment=5),
    ShopData("406", atmosphere=9, health=5),
    ShopData("406", atmosphere=9, health=5),
    ShopData("407", entertainment=9, liability=5, revenue=5),
    ShopData("408", atmosphere=1, entertainment=7, revenue=1),
    ShopData("409", entertainment=3, revenue=8),
    ShopData("410", health=9, entertainment=7),
    ShopData("411", entertainment=9, liability=9),
    ShopData("412", entertainment=9, liability=1),
    ShopData("413", atmosphere=7, entertainment=7),
    ShopData("414", atmosphere=9, entertainment=9, revenue=9),
    ShopData("415"),
]


item_table = {
    "Molten Freddy": ItemData(55503, ItemClassification.progression, "m2"),
    "ScrapTrap": ItemData(55500, ItemClassification.progression, "m3"),
    "Scrap Baby": ItemData(55501, ItemClassification.progression, "m4"),
    "Lefty": ItemData(55502, ItemClassification.progression, "m5"),
    "Balloon Barrel Decor": ItemData(55649, ItemClassification.progression_skip_balancing, "101"),
    "Ballpit Decor": ItemData(55645, ItemClassification.progression_skip_balancing, "102"),
    "Sanitation Station Decor": ItemData(55618, ItemClassification.useful, "107"),
    "Discount Cooling Unit Decor": ItemData(55656, ItemClassification.useful, "108"),
    "Duck Pond Decor": ItemData(55644, ItemClassification.progression_skip_balancing, "109"),
    "Bucket Bob Animatronic": ItemData(55626, ItemClassification.useful, "110"),
    "Mr Can Do Animatronic": ItemData(55639, ItemClassification.useful, "111"),
    "Mr Hugs Animatronic": ItemData(55620, ItemClassification.useful, "112"),
    "No. 1 Crate Animatronic": ItemData(55638, ItemClassification.useful, "113"),
    "Pan Stan Animatronic": ItemData(55625, ItemClassification.useful, "114"),
    "Paper Pals Decor": ItemData(55622, ItemClassification.useful, "115"),
    "Fruit Maze Decor": ItemData(55610, ItemClassification.progression_skip_balancing, "204"),
    "Midnight Motorist Decor": ItemData(55623, ItemClassification.progression_skip_balancing, "205"),
    "Gumball Machine Decor": ItemData(55619, ItemClassification.useful, "206"),
    "Stage Light Decor": ItemData(55631, ItemClassification.useful, "207"),
    "Traffic Light Decor": ItemData(55652, ItemClassification.useful, "210"),
    "Happy Frog Animatronic": ItemData(55609, ItemClassification.useful, "211"),
    "Mr Hippo Animatronic": ItemData(55633, ItemClassification.useful, "212"),
    "Nedd Bear Animatronic": ItemData(55634, ItemClassification.useful, "213"),
    "Pig Patch Animatronic": ItemData(55632, ItemClassification.useful, "214"),
    "Candy Cadet Decor": ItemData(55642, ItemClassification.progression_skip_balancing, "215"),
    "Side Stage Upgrade": ItemData(55646, ItemClassification.useful, "301"),
    "Ballpit Tower Decor": ItemData(55651, ItemClassification.progression_skip_balancing, "303"),
    "Ladder Tower Decor": ItemData(55627, ItemClassification.progression_skip_balancing, "304"),
    "Carnival Hoops Decor": ItemData(55650, ItemClassification.progression_skip_balancing, "305"),
    "Roller Coaster Decor": ItemData(55611, ItemClassification.progression_skip_balancing, "306"),
    "Lemonade Clown Decor": ItemData(55636, ItemClassification.progression_skip_balancing, "307"),
    "Punch Clown Decor": ItemData(55616, ItemClassification.progression_skip_balancing, "308"),
    "Jukebox Decor": ItemData(55643, ItemClassification.useful, "309"),
    "Medical Station Decor": ItemData(55629, ItemClassification.useful, "310"),
    "Security Door Decor": ItemData(55630, ItemClassification.useful, "311"),
    "Rockstar Freddy Animatronic": ItemData(55640, ItemClassification.useful, "312"),
    "Rockstar Bonnie Animatronic": ItemData(55635, ItemClassification.useful, "313"),
    "Rockstar Chica Animatronic": ItemData(55648, ItemClassification.useful, "314"),
    "Rockstar Foxy Animatronic": ItemData(55647, ItemClassification.useful, "315"),
    "Balloon Cart Decor": ItemData(55607, ItemClassification.progression_skip_balancing, "401"),
    "Confetti Floor": ItemData(55612, ItemClassification.useful, "402"),
    "Deluxe Ballpit Decor": ItemData(55653, ItemClassification.progression_skip_balancing, "403"),
    "Pizza Light Decor": ItemData(55614, ItemClassification.useful, "404"),
    "Data Archive Decor": ItemData(55605, ItemClassification.useful, "405"),
    "Gravity Vortex Decor": ItemData(55641, ItemClassification.progression_skip_balancing, "407"),
    "Orville Elephant Animatronic": ItemData(55621, ItemClassification.useful, "408"),
    "Prize King Decor": ItemData(55617, ItemClassification.useful, "409"),
    "Security Puppet Decor": ItemData(55615, ItemClassification.progression_skip_balancing, "410"),
    "Lefty Animatronic": ItemData(55604, ItemClassification.useful, "411"),
    "Music Man Animatronic": ItemData(55628, ItemClassification.progression, "412"),
    "El Chip Animatronic": ItemData(55624, ItemClassification.progression, "413"),
    "Funtime Chica Animatronic": ItemData(55637, ItemClassification.progression, "414"),
    "Pickles Decor": ItemData(55608, ItemClassification.useful, "415"),
    "Stage Upgrade": ItemData(55613, ItemClassification.progression, "stage"),
    "Cup Upgrade": ItemData(55654, ItemClassification.useful, "cups"),
    "Speaker Upgrade": ItemData(55655, ItemClassification.useful, "speakers"),
    "Catalogue 2 Unlock": ItemData(55557, ItemClassification.progression, "un1"),
    "Catalogue 3 Unlock": ItemData(55558, ItemClassification.progression, "un2"),
    "Catalogue 4 Unlock": ItemData(55559, ItemClassification.progression, "un3"),
    "Printer Upgrade": ItemData(55560, ItemClassification.useful, "printer"),
    "Handyman Upgrade": ItemData(55561, ItemClassification.useful, "handyman"),
    "Internet Upgrade": ItemData(55562, ItemClassification.useful, "hispeed"),
    "Wallet Capacity Increase": ItemData(55563, ItemClassification.progression, "maxmoney"),
    "250 Money": ItemData(55564, ItemClassification.filler, "money"),
    "Tuesday Unlock": ItemData(55565, ItemClassification.progression, "day2"),
    "Wednesday Unlock": ItemData(55566, ItemClassification.progression, "day3"),
    "Thursday Unlock": ItemData(55567, ItemClassification.progression, "day4"),
    "Friday Unlock": ItemData(55568, ItemClassification.progression, "day5"),
    "Saturday Unlock": ItemData(55569, ItemClassification.progression, "day6"),
}

lookup_id_to_name: typing.Dict[int, str] = {data.code: item_name for item_name, data in item_table.items() if data.code}
